# Generated by Django 3.2.3 on 2021-06-11 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0002_auto_20210611_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
