# Generated by Django 3.2.3 on 2021-06-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0003_alter_statement_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='item_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
