# Generated by Django 3.2.3 on 2021-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0006_auto_20210613_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata_64',
            name='parent_gender',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='campdata_64',
            name='parent_relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campdata_64',
            name='parent_surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
