# Generated by Django 3.2.3 on 2021-06-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0007_auto_20210613_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campdata_64',
            name='registered',
        ),
    ]
