# Generated by Django 3.2.3 on 2021-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0013_campdata_63'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp_registered_64',
            old_name='registered_by',
            new_name='registered_by_1',
        ),
        migrations.AddField(
            model_name='camp_registered_64',
            name='registered_by_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
