# Generated by Django 3.2.3 on 2021-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0004_auto_20210610_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='eedata_63',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
