# Generated by Django 3.2.3 on 2021-06-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0005_eedata_63_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eedata_63',
            options={'verbose_name': 'EEData63', 'verbose_name_plural': 'EEData63'},
        ),
        migrations.AlterModelOptions(
            name='eeuserprofile',
            options={'verbose_name': 'EEUserProfile', 'verbose_name_plural': 'EEUserProfile'},
        ),
        migrations.DeleteModel(
            name='EEData_64',
        ),
        migrations.CreateModel(
            name='EEData_64',
            fields=[
            ],
            options={
                'verbose_name': 'EEData64',
                'verbose_name_plural': 'EEData64',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('site_auth.eedata_63',),
        ),
    ]
