# Generated by Django 3.2.3 on 2021-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0007_auto_20210611_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeuserprofile',
            name='allergic_foods',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eeuserprofile',
            name='allergic_meds',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eeuserprofile',
            name='congenital_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eeuserprofile',
            name='religion',
            field=models.CharField(choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('อื่นๆ', 'อื่นๆ')], max_length=6, null=True),
        ),
    ]
