# Generated by Django 3.2.3 on 2021-06-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('preelec9_camp', '0004_statement_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campdata_64',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('shirt_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=100)),
                ('passion', models.CharField(max_length=1000, null=True)),
                ('parent_telephone_num', models.CharField(max_length=10, null=True)),
                ('parent_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'CampData64',
                'verbose_name_plural': 'CampData64',
            },
        ),
    ]
