# Generated by Django 3.2.3 on 2021-06-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0005_campdata_64'),
    ]

    operations = [
        migrations.AddField(
            model_name='campdata_64',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campdata_64',
            name='house',
            field=models.CharField(choices=[('AR', 'Ares'), ('PO', 'Poseidon'), ('ZE', 'Zeus'), ('HE', 'Hermes')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='campdata_64',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
