# Generated by Django 3.2.3 on 2021-06-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0009_auto_20210614_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campdata_64',
            name='registered_1_ts',
        ),
        migrations.RemoveField(
            model_name='campdata_64',
            name='registered_2_ts',
        ),
        migrations.RemoveField(
            model_name='campdata_64',
            name='registered_3_ts',
        ),
        migrations.RemoveField(
            model_name='campdata_64',
            name='registered_fin_ts',
        ),
    ]
