# Generated by Django 3.2.3 on 2021-06-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0011_camp_registered_64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp_registered_64',
            old_name='registered_on',
            new_name='registered_on_1',
        ),
        migrations.AddField(
            model_name='camp_registered_64',
            name='registered_on_2',
            field=models.DateTimeField(null=True),
        ),
    ]
