# Generated by Django 3.2.3 on 2021-06-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0015_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='check_shirt',
        ),
        migrations.AddField(
            model_name='campdata_63',
            name='check_shirt',
            field=models.ImageField(null=True, upload_to='images/preelec9_camp/shirt'),
        ),
    ]
