# Generated by Django 3.2.3 on 2021-06-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0016_auto_20210622_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='quantity_shirt',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
