# Generated by Django 3.2.3 on 2021-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0017_alter_shirt_quantity_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campdata_63',
            name='check_shirt',
            field=models.ImageField(null=True, upload_to='images/preelec9_camp/shirt', verbose_name='หลักฐานการโอน'),
        ),
        migrations.AlterField(
            model_name='campdata_64',
            name='shirt_size',
            field=models.CharField(choices=[('SS', 'SS (34"/26")'), ('S', 'S (36"/27")'), ('M', 'M (38"/28")'), ('L', 'L (40"/29")'), ('XL', 'XL (42"/30")'), ('XXL', 'XXL (44"/31")')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='color_shirt',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='quantity_shirt',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='size_shirt',
            field=models.CharField(choices=[('SS', 'SS (34"/26")'), ('S', 'S (36"/27")'), ('M', 'M (38"/28")'), ('L', 'L (40"/29")'), ('XL', 'XL (42"/30")'), ('XXL', 'XXL (44"/31")')], max_length=100),
        ),
    ]
