# Generated by Django 3.2.3 on 2021-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec9_camp', '0019_campdata_6x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='division',
            field=models.CharField(choices=[('Art', 'Art'), ('Data', 'Data'), ('Delivery', 'Delivery'), ('Local', 'Local'), ('Medic', 'Medic'), ('PR', 'PR'), ('Recreation', 'Recreation'), ('Security', 'Security'), ('Secretary', 'Secretary'), ('Welfare', 'Welfare'), ('Treasurer', 'Treasurer'), ('Welcome Box', 'Welcome Box'), ('Other', 'Other')], max_length=100),
        ),
    ]
