# Generated by Django 3.2.3 on 2021-07-04 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerbank_color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('shop_choices', models.CharField(choices=[('powerbank', 'Powerbank'), ('bag', 'Bag')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Size_shirt',
                'verbose_name_plural': 'Size_shirt',
            },
        ),
        migrations.CreateModel(
            name='Camp_online_6x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_shop', models.ImageField(null=True, upload_to='images/preelec_online/shop', verbose_name='หลักฐานการโอน')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camp_online_6x',
                'verbose_name_plural': 'Camp_online_6x',
            },
        ),
        migrations.CreateModel(
            name='Camp_online_64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camp_online_64',
                'verbose_name_plural': 'Camp_online_64',
            },
        ),
    ]
