# Generated by Django 3.2.3 on 2021-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp_online_6x',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
