# Generated by Django 3.2.3 on 2021-07-04 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0002_camp_online_6x_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.AddField(
            model_name='shop',
            name='camp_online_6x',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preelec_online.camp_online_6x'),
        ),
    ]
