# Generated by Django 3.2.3 on 2021-07-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0003_auto_20210704_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='powerbank_color',
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
