# Generated by Django 3.2.3 on 2021-07-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0008_shop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_choices',
            field=models.CharField(choices=[('Powerbank', 'Powerbank'), ('Bag', 'Bag')], max_length=100),
        ),
    ]
