# Generated by Django 3.2.3 on 2021-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0010_camp_online_6x_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, null=True)),
                ('activity_date', models.DateField(null=True)),
                ('activity_beginning_time', models.TimeField(null=True)),
                ('activity_end_time', models.TimeField(null=True)),
                ('activity_description', models.CharField(max_length=100, null=True)),
                ('activity_caretaker', models.CharField(max_length=100, null=True)),
                ('activity_place', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Activity_Camp',
                'verbose_name_plural': 'Activity_Camp',
            },
        ),
    ]
