# Generated by Django 3.2.3 on 2021-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0011_activity_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp_online_6x',
            name='Sented',
            field=models.BooleanField(default=False),
        ),
    ]
