# Generated by Django 3.2.3 on 2021-07-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0012_camp_online_6x_sented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camp_online_6x',
            old_name='Sented',
            new_name='sent',
        ),
    ]
