# Generated by Django 3.2.3 on 2021-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preelec_online', '0013_rename_sented_camp_online_6x_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp_online_64',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
