# Generated by Django 3.2.3 on 2021-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eeuserprofile',
            options={'verbose_name': 'EEUserProfile'},
        ),
        migrations.AddField(
            model_name='eeuserprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
