# Generated by Django 3.2.3 on 2021-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0003_auto_20210610_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eedata_63',
            options={'verbose_name': 'EEData63'},
        ),
        migrations.AlterModelOptions(
            name='eedata_64',
            options={'verbose_name': 'EEData64'},
        ),
        migrations.AddField(
            model_name='eedata_63',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eedata_63',
            name='self_telephone_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eeuserprofile',
            name='self_telephone_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
