# Generated by Django 3.2.3 on 2021-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0009_eedata_61_eedata_62'),
    ]

    operations = [
        migrations.AddField(
            model_name='eedata_61',
            name='email2',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eedata_62',
            name='email2',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eedata_63',
            name='email2',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eedata_64',
            name='email2',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
