# Generated by Django 3.2.3 on 2021-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0010_auto_20210706_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeuserprofile',
            name='eng_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eeuserprofile',
            name='eng_surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
